[project]
name = "notes-app-joltnotes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "appdirs>=1.4.4",
    "customtkinter>=5.2.2",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.14.0",
]
